name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy project to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "." # Copies the entire project directory
          target: ${{ secrets.TARGET_PATH }}
          rm: true

      - name: Build and Run Docker Container on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            pwd
            cd {{ secrets.TARGET_PATH }}
            cat <<EOF > .env
            TELEGRAM_BOT_NAME=${{ secrets.TELEGRAM_BOT_NAME }}
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            TG_ADMIN=${{ secrets.TG_ADMIN }}
            MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}
            EOF
            docker-compose up --build -d
